---
---
# Advanced Analytics

Objectives:-
1. Identify high-value vs low-value customers.
2. Support customer strategy.

---
Import Libraries:-

In [ ]:
import pandas as pd
import numpy as np

---
Load Clean Data:-

In [ ]:
file_path = ('../Data/02_Clean_Data/MM_Clean_Data.csv')
df = pd.read_csv(file_path)

df["Date"] = pd.to_datetime(df["Date"])
df.head()

---
Data Preparation for Advanced Analysis:-

In [ ]:
df_advanced = df[[
    "Region", 
    "Customer_Type", 
    "Revenue_USD", 
    "Profit_Margin_%", 
    "Discount_%"
]].copy()

---
Part 1: Customer Segmentation:


Apply KMeans Clustering:-

In [ ]:
from sklearn.cluster import KMeans

X = df_advanced[["Revenue_USD", "Profit_Margin_%"]]

kmeans = KMeans(n_clusters=3, random_state = 42)
df_advanced["Cluster"] = kmeans.fit_predict(X)

---
Analyze Cluster Characteristics:-

In [ ]:
Cluster_Summary = df_advanced.groupby("Cluster").agg({
    "Revenue_USD": "mean",
    "Profit_Margin_%": "mean",
    "Customer_Type": "count"
}).rename(columns={"Customer_Type": "Customer_Count"})

Cluster_Summary

---
Part 2: Market Expansion Analysis:

Region-wise Performance:-

In [24]:
Region_Analysis = df.groupby("Region").agg({
    "Revenue_USD": "sum",
    "Profit_USD": "sum",
    "Units_Sold": "sum"
})

Region_Analysis

                      Revenue_USD    Profit_USD  Units_Sold
Region
Asia                   3445292400  8.630458e+08      123091
Asia-Pacific           3473935300  8.677780e+08      124235
Europe                 6929869900  1.730176e+09      248230
Middle East & Africa   3485426600  8.731211e+08      124616
North America          3454877100  8.619447e+08      123564

---
Identify High Growth Markets:-

In [25]:
Region_Analysis["Profit_Margin_%"] = (
    Region_Analysis["Profit_USD"] / Region_Analysis["Revenue_USD"]
) * 100

Region_Analysis.sort_values(by = "Revenue_USD", ascending = False)

                      Revenue_USD    Profit_USD  Units_Sold  Profit_Margin_%
Region
Europe                 6929869900  1.730176e+09      248230        24.966940
Middle East & Africa   3485426600  8.731211e+08      124616        25.050625
Asia-Pacific           3473935300  8.677780e+08      124235        24.979682
North America          3454877100  8.619447e+08      123564        24.948635
Asia                   3445292400  8.630458e+08      123091        25.050003

---
Part 3: Scenario Analysis (Customer Strategy):

Scenario 1: Discount Increase Impact:-

In [26]:
df["New_Revenue"] = df["Revenue_USD"] * 1.05

---
Compare Old vs New Revenue:-

In [27]:
Comparison = df[["Revenue_USD", "New_Revenue"]].sum()
Comparison

Revenue_USD    2.078940e+10
New_Revenue    2.182887e+10
dtype: float64

---
Scenario 2: Profit Impact:-

In [28]:
df["New_Profit"] = df["New_Revenue"] - df["Cost_USD"]
Profit_Comparison = df[["Profit_USD", "New_Profit"]].sum()
Profit_Comparison

Profit_USD    5.196066e+09
New_Profit    6.235536e+09
dtype: float64

---
---